
> deedlockerpi@0.0.0 start
> node ./app.js

Dec 23, 2022 23:14 [[32minfo[39m]: /home/pi/DeedLockerPi-NodeServer 
Dec 23, 2022 23:14 [[32minfo[39m]: Server Running in development mode on port 4000 
Dec 23, 2022 23:17 [[32minfo[39m]: Rendering Index 
Dec 23, 2022 23:17 [[32minfo[39m]: Write Mode 
6376ab7a63848432ea56a1d2
Dec 23, 2022 23:18 [[32minfo[39m]: stderr: Traceback (most recent call last):
  File "/home/pi/DeedLockerPi/write_boxId.py", line 6, in <module>
 
Dec 23, 2022 23:18 [[32minfo[39m]: stderr:     from serverUtils import *
  File "/home/pi/DeedLockerPi/serverUtils.py", line 2, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
 
Dec 23, 2022 23:19 [[32minfo[39m]: Write Mode 
6376b8247fb40a4caf9d10f1
Dec 23, 2022 23:20 [[32minfo[39m]: Response from RPI 
{
  code: 200,
  data: '',
  message: 'Writing 6376b8247fb40a4caf9d10f1 to RFID'
}
Dec 23, 2022 23:20 [[32minfo[39m]: stderr: Traceback (most recent call last):
  File "/home/pi/DeedLockerPi/write_boxId.py", line 58, in <module>
    pn532 = configurePN532()
  File "/home/pi/DeedLockerPi/write_boxId.py", line 10, in configurePN532
 
Dec 23, 2022 23:20 [[32minfo[39m]: stderr:     pn532 = PN532_UART(debug=False, reset=20)
  File "/home/pi/DeedLockerPi/pn532/uart.py", line 58, in __init__
    self._gpio_init(irq=irq, reset=reset)
  File "/home/pi/DeedLockerPi/pn532/uart.py", line 68, in _gpio_init
 
Dec 23, 2022 23:20 [[32minfo[39m]: stderr:     GPIO.setup(reset, GPIO.OUT)
RuntimeError: No access to /dev/mem.  Try running as root!
 
Dec 23, 2022 23:21 [[32minfo[39m]: Write Mode 
